@startuml



interface DomainViewI.EditorControlerAdapter_EXC_I{
}
interface DomainViewI.DirectoryNode_EXC_I{
}
interface DomainViewI.FileNode_EXC_I{
}
interface DomainViewI.StorageNode2_EXC_I{
}
DomainViewI.EditorControlerAdapter_EXC_I --> DomainViewI.DirectoryNode_EXC_I : use
DomainViewI.EditorControlerAdapter_EXC_I --> DomainViewI.StorageNode2_EXC_I : use
DomainViewI.EditorControlerAdapter_EXC_I --> DomainViewI.FileNode_EXC_I : use



View.TabCreator  --> View.TabManger : use
View.TabCreator  --> DomainViewI.EditorControlerAdapter_EXC_I : use
View.TabCreator  --> View.FileDiv : use
View.TabCreator  --> View.TABpage : use

View.TabManger --> View.ViewObjectCreator : use
View.TabManger --> View.CanalAdapter : use
View.TabManger --> technical.Observer : use
View.TabManger --> View.FileDiv : use
View.TabManger --> View.TabCreator : use
View.TabManger --> View.TabManager_I : use

View.ContextMenu -> View.StorageDiv : use

View.DirectoryDiv -> DomainViewI.DirectoryNode_EXC_I : use
View.DirectoryDiv --> DomainViewI.EditorControlerAdapter_EXC_I  : use
View.DirectoryDiv -> View.TabCreator : use
View.DirectoryDiv -> View.ContextMenu : use
View.DirectoryDiv -> View.FileDiv : use
View.DirectoryDiv  --|> View.StorageDiv : exdend

View.FileDiv  --> DomainViewI.EditorControlerAdapter_EXC_I  : use
View.FileDiv  ---> DomainViewI.FileNode_EXC_I : use
View.FileDiv  -->  View.ContextMenu : use
View.FileDiv  --> View.FileLeftClickMenu : use
View.FileDiv  --|> View.StorageDiv : exdend
View.FileDiv  -->  View.TabCreator : use



View.FileExplorerDiv -> View.DirectoryDiv : use
View.FileExplorerDiv --> View.FileDiv : use
View.FileExplorerDiv --> View.StorageDiv : use
View.FileExplorerDiv --> View.TabManager_I : use
View.FileExplorerDiv <|-- View.FileManager_I : implements
View.FileExplorerDiv -> DomainViewI.DirectoryNode_EXC_I : use
View.FileExplorerDiv -> DomainViewI.EditorControlerAdapter_EXC_I : use
View.FileExplorerDiv -> DomainViewI.FileNode_EXC_I : use


View.StorageDiv --> DomainViewI.EditorControlerAdapter_EXC_I  : use
View.StorageDiv ---> DomainViewI.StorageNode2_EXC_I : use
View.StorageDiv -> technical.ObservableI : use
View.StorageDiv -> technical.Observer : use


View.FileLeftClickMenu -> View.FileDiv : use









Domain.EditorControlerAdapter -->  DomainViewI.DirectoryNode_EXC_I : use
Domain.EditorControlerAdapter -->  DomainViewI.FileNode_EXC_I : use
Domain.EditorControlerAdapter -->  DomainViewI.StorageNode2_EXC_I : use
Domain.EditorControlerAdapter -->  DomainViewI.EditorControlerAdapter_EXC_I : use

Domain.EditorControlerAdapter -->  Domain.DirectoryNode : use
Domain.EditorControlerAdapter -->  Domain.FileNode : use
Domain.EditorControlerAdapter -->  Domain.StorageNode2 : use

Domain.FileNode --|>  Domain.StorageNode2 : exend
Domain.FileNode -->  DomainViewI.FileNode_EXC_I : impement

Domain.StorageNode2 --|>  technical.Observable : exend
Domain.StorageNode2 -->  technical.Observer : impement
Domain.StorageNode2 -->  DomainViewI.StorageNode2_EXC_I : impement


Domain.DirectoryNode --|>  Domain.StorageNode2 : exend
Domain.DirectoryNode -->  DomainViewI.DirectoryNode_EXC_I : impement
Domain.DirectoryNode -->  Domain.FileNode : impement

@enduml

